trigger:
  tags:
    include:
    - '*'

pr: none

pool:
  vmImage: 'macOS-14'

stages:
- stage: Build
  jobs:
  - job: Android
    steps:
    - task: JavaToolInstaller@0
      displayName: Use Java 17
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
        
    - task: FlutterInstall@0
      displayName: Install Flutter
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'custom'
        customVersion: '3.32.4'

    - task: DownloadSecureFile@1
      displayName: Download dictionarykeystore
      inputs:
        secureFile: 'dictionarykeystore'

    - task: file-creator@6
      displayName: Create key.properties
      inputs:
        filepath: './android/key.properties'
        filecontent: |
          storePassword=$(android.storePassword)
          keyPassword=$(android.keyPassword)
          keyAlias=$(android.keyAlias)
          storeFile=$(Agent.TempDirectory)/dictionarykeystore
        fileoverwrite: true

    - task: FlutterBuild@0
      displayName: Build
      inputs:
        target: 'aab'
        projectDirectory: '.'
      
    - task: CopyFiles@2
      displayName: Copy aab
      inputs:
        SourceFolder: 'build/app/outputs/bundle/release'
        Contents: '*.aab'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishPipelineArtifact@1
      displayName: Publish aab
      inputs:
        path: $(Build.ArtifactStagingDirectory)
        artifact: android

- stage: Publish
  jobs:
  - deployment: Internal
    pool:
      vmImage: 'ubuntu-latest'
    environment: Internal
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'android'
              targetPath: '$(Pipeline.Workspace)'
              
          - task: GooglePlayRelease@4
            displayName: Publish to Google Play Internal Test
            inputs:
              serviceConnection: 'Google Play'
              applicationId: 'ru.bacr.dictionary'
              action: 'SingleBundle'
              bundleFile: '$(Pipeline.Workspace)/**/*.aab'
              track: 'internal'
              languageCode: 'ru-RU'