# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

pool:
  vmImage: 'macOS-latest'

variables:
  SDK: iphoneos
  Configuration: Release

stages:
- stage: Build
  jobs:
  - job: iOS
    steps:
    - task: FlutterInstall@0
      displayName: Install Flutter
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'custom'
        customVersion: '3.22.0'
    
    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'AppleCertificate.p12'
        certPwd: '$(CertificatePassword)'
        keychain: 'temp'
    
    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'SakhaTyla.mobileprovision'
        
    - task: FlutterBuild@0
      displayName: Build
      inputs:
        target: 'ios'
        projectDirectory: '.'
        buildNumber: 
        iosCodesign: false
    
    - task: Xcode@5
      displayName: Archive
      inputs:
        actions: 'archive'
        xcWorkspacePath: '**/Runner.xcworkspace'
        scheme: 'Runner'
        packageApp: true
        signingOption: 'manual'
        signingIdentity: 'Apple Distribution: Vassily Ivanov (898MZ6K4Y5)'
        provisioningProfileName: 'SakhaTyla'
      
    - task: CopyFiles@2
      displayName: Copy ipa
      inputs:
        SourceFolder: 'output/$(SDK)/$(Configuration)'
        Contents: '*.ipa'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishPipelineArtifact@1
      displayName: Publish ipa
      inputs:
        path: $(Build.ArtifactStagingDirectory)
        artifact: ios

- stage: Publish
  jobs:
  - deployment: TestFlight
    pool:
      vmImage: 'macOS-latest'
    environment: Internal
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'ios'
              targetPath: '$(Pipeline.Workspace)'
          
          - task: AppStoreRelease@1
            inputs:
              serviceEndpoint: 'App Store'
              appIdentifier: 'ru.sakhatyla.app'
              appType: 'iOS'
              ipaPath: '$(Pipeline.Workspace)/ios/*.ipa'
              releaseTrack: 'TestFlight'
              teamId: '121372496'
